// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzLnwwDCnn6ZmUZHHPPh4NnHPoKx7adMI',
    appId: '1:739439465191:web:81e01a0d842af186f44842',
    messagingSenderId: '739439465191',
    projectId: 'pesandokter-3c319',
    authDomain: 'pesandokter-3c319.firebaseapp.com',
    storageBucket: 'pesandokter-3c319.appspot.com',
    measurementId: 'G-BVYE1LQ57V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAF_zLlDgUDAWSfQNk5GdVdS5OUoQfYzws',
    appId: '1:739439465191:android:1e28505e93e5ca0ef44842',
    messagingSenderId: '739439465191',
    projectId: 'pesandokter-3c319',
    storageBucket: 'pesandokter-3c319.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsC7iVSBMcNDGfK7vnZTBDnzfaVQO1K_4',
    appId: '1:739439465191:ios:21b503c28daa41ddf44842',
    messagingSenderId: '739439465191',
    projectId: 'pesandokter-3c319',
    storageBucket: 'pesandokter-3c319.appspot.com',
    iosClientId: '739439465191-nf9g644mn9vl29okm0j28uvesa0l7id1.apps.googleusercontent.com',
    iosBundleId: 'com.pesandokter.pesandokter',
  );
}
